env:
  browser: true
  es6: true

parser: babel-eslint
extends:
  - airbnb-base
  - 'plugin:lodash-fp/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0

plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
